insert into User(id, name, password, email, account_state) values (101,'Ashi', 'Ashi','Ashi@gmail.com','Active');
insert into User(id, name, password, email, account_state) values (105,'Ashi', 'Ashi','Ashi1@gmail.com','InActive');
insert into User(id, name, password, email, account_state) values (106,'Ashi', 'Ashi','Ashi2@gmail.com','Active');
insert into User(id, name, password, email, account_state) values (102,'Bindal', 'Bindal','Bindal@gmail.com','Active');
insert into User(id, name, password, email, account_state) values (103,'Ramesh', 'Ramesh','Ramesh@gmail.com','Active');
insert into User(id, name, password, email, account_state) values (104,'Suresh', 'Suresh','Suresh@gmail.com','Active');
INSERT into user_roles values (101,'Admin'); 
INSERT into user_roles values (102,'User'); 
INSERT into user_roles values (103,'User'); 
INSERT into user_roles values (104,'User'); 
insert into address(users_id,city,pincode,State) values(101,'Dwarka',110075,'Delhi');
insert into address(users_id,city,pincode,State) values(103,'GZB',110111,'UP');
insert into address(users_id,city,pincode,State) values(104,'MZN',251002,'UP');